# Generated by Django 4.2.7 on 2023-11-30 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название категории', max_length=255, verbose_name='Наименование категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название продукта', max_length=255, verbose_name='Наименование продукта')),
                ('price', models.FloatField(help_text='Введите цену продукта', verbose_name='Цена')),
                ('stock', models.IntegerField(help_text='Введите количество продукта на складе', verbose_name='Остаток')),
                ('description', models.TextField(blank=True, help_text='Введите описание продукта', verbose_name='Описание')),
                ('added_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время добавления продукта', verbose_name='Дата добавления')),
                ('is_active', models.BooleanField(default=True, help_text='Флаг активности продукта', verbose_name='Активен')),
                ('category', models.ForeignKey(help_text='Выберите категорию продукта', on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
